---
driver:
  name: vagrant
  network:
    - ['forwarded_port', {guest: 8111, host: 8111}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[teamcity::default]
